#%RAML 1.0
---
title: Business Source Adjustable Summary (MTD)
description: Retrieve an adjustable summary calculation for a specified self-employment or property business, for a given accounting period.
version: 3.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/individuals/self-assessment/adjustable-summary':
    uriParameters:
      nino:
        description: National Insurance number in the format AA999999A.
        type: string
        example: TC663795B
    /{nino}:
      /self-employment/{calculationId}:
        (annotations.group):
          name: Self Employment Business
          description: ""
        uriParameters:
          calculationId:
            description: 'The unique identifier of the summary calculation.<br><br>Must conform to the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
            type: string
            example: 717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4
        get: !include retrieve_property_bsas.raml
      /property/{calculationId}:
        (annotations.group):
          name: UK Property Business
          description: ""
        uriParameters:
          calculationId:
            description: 'The unique identifier of the summary calculation.<br><br>Must conform to the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
            type: string
            example: 717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4
        get: !include retrieve_property_bsas.raml