is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBsasId
  - errors.ruleNotForeignProperty
  - errors.ruleNoAdjustmentsMade
  - errors.clientOrAgentNotAuthorised
  - errors.bsasNotFound
displayName: Retrieve a Foreign property Business Source Adjustable Summary (BSAS) [test only]
description: This endpoint allows the user to request a specific Business Source Adjustable Summary for a Foreign property business EEA Furnished Holiday Letting (FHL) or a Non FHL Foreign property business. A National Insurance number and Calculation id must be provided.
(annotations.sandboxData): !include scenarios/retrieve_foreign_property_adjustments.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_foreign_property_adjustments.json
        examples:
          adjustments_full:
            description: Retrieve Foreign Property Business' Summary Adjustments example
            value: !include examples/adjustments/retrieve_foreign_property_adjustments.json
          adjustments_fhleea:
            description: Retrieve Foreign Property FhlEea Business' Summary Adjustments example
            value: !include examples/adjustments/retrieve_foreign_property_adjustments_fhl_eea.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.