is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatCalculationId
  - errors.formatValue
  - errors.ruleBothExpensesSupplied
  - errors.ruleTypeOfBusinessIncorrectSE
  - errors.incorrectOrEmptyBodySubmitted
  - errors.clientOrAgentNotAuthorised
  - errors.ruleSummaryStatusInvalid
  - errors.ruleSummaryStatusSuperseded
  - errors.ruleAlreadyAdjusted
  - errors.ruleResultingValueNotPermitted
  - errors.ruleOverConsolidatedExpensesThreshold
  - errors.ruleTradingIncomeAllowanceExceeded
  - errors.adjustmentNotFound
displayName: Submit Self-Employment Accounting Adjustments
description: This endpoint allows the user to provide accounting adjustments against a specified Business Source Accounting Summary quoting its unique identifier. The calculation ID quoted must be for a Self-Employment Business and it must not have been adjusted previously. A National Insurance number and calculation ID must be provided.
(annotations.sandboxData): !include scenarios/submit_se_adjustments.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/submit_se_adjustments.json
    examples:
      adjustments_full:
        description: Full Expenses
        value: !include examples/adjustments/submit_se_adjustments_full.json
      adjustments_consolidated:
        description: Consolidated Expenses
        value: !include examples/adjustments/submit_se_adjustments_consolidated.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/submit_adjustments_response.json
        example: !include examples/adjustments/submit_se_adjustment_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.