openapi: "3.0.3"

info:
  version: "6.0"
  title: Business Source Adjustable Summary (MTD)
  description: |
    Retrieve an adjustable summary calculation for a specified self-employment or property business, for a given
    accounting period.
    
    # Send fraud prevention data
    HMRC monitors transactions to help protect your customers' confidential data from criminals and fraudsters. 
    
    <div class="govuk-warning-text warning-icon-fix">
      <span class="govuk-warning-text__icon warning-icon-ui-fix" aria-hidden="true">!</span>
      <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        You are required by law to submit header data for this API. This includes all associated APIs and endpoints.
      </strong>
    </div>
    
    [Check the data you need to send](/guides/fraud-prevention/). You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/1.0) 
    during initial development and as part of your quality assurance checks.

    # Changelog
    You can find the changelog in the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/#readme) GitHub wiki.

    # Support

    * Direct reports of bugs or errors in Production or Sandbox code, or queries about HMRC business functionality (such as how a specific field is used by HMRC or why it is needed) to the [Software Development Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).
    * Send queries or feedback related to the design of the APIs (including recommended changes) using the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues) GitHub page.
    * <a href="/contact/report-technical-problem?newTab=true&service=api-documentation-frontend" target="_blank">Is this page not working properly? (opens in new tab)</a>

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access

tags:
  - name: Self-employment business
    description: Resources relating to Self-employment business
  - name: UK property business
    description: Resources relating to UK property business
  - name: Foreign property business
    description: Resources relating to Foreign property business


paths:
  /individuals/self-assessment/adjustable-summary/{nino}/{taxYear}:
    $ref: ./bsas_list.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/trigger:
    $ref: ./bsas_trigger.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/self-employment/{calculationId}/{taxYear}:
    $ref: ./self_employment_retrieve.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/self-employment/{calculationId}/adjust/{taxYear}:
    $ref: ./self_employment_adjustments_submit.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/uk-property/{calculationId}/{taxYear}:
    $ref: ./uk_property_bsas_retrieve.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/uk-property/{calculationId}/adjust/{taxYear}:
    $ref: ./uk_property_accounting_adjustments_submit.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/foreign-property/{calculationId}/{taxYear}:
    $ref: ./foreign_property_retrieve.yaml
  /individuals/self-assessment/adjustable-summary/{nino}/foreign-property/{calculationId}/adjust/{taxYear}:
    $ref: ./foreign_property_accounting_adjustments_submit.yaml
