#%RAML 1.0
---
title: Business Source Adjustable Summary (MTD)
description: This is a spec for the Business Source Adjustable Summary API
version: 2.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/individuals/self-assessment/adjustable-summary':
  uriParameters:
    nino:
      description: National Insurance number in the format AA999999A.
      type: string
      example: TC663795B
  /{nino}:
    get: !include list.raml
    /trigger:
      post: !include trigger.raml
    /self-employment/{bsasId}:
      (annotations.group):
          name: Self-employment business
          description: ""
      uriParameters:
        bsasId:
          description: 'The unique identifier of the summary calculation.<br><br>Must conform to the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
          type: string
          example: f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c
      get: !include retrieve_se_bsas.raml
      /adjust:
        post: !include submit_se_adjustments.raml
        get: !include retrieve_se_adjustments.raml
    /property/{bsasId}:
      (annotations.group):
          name: UK property business
          description: ""
      uriParameters:
        bsasId:
          description: 'The unique identifier of the summary calculation.<br><br>Must conform to the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
          type: string
          example: f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c
      get: !include retrieve_property_bsas.raml
      /adjust:
        post: !include submit_property_adjustments.raml
        get: !include retrieve_property_adjustments.raml
    /foreign-property/{bsasId}:
      (annotations.group):
        name: Foriegn property business
        description: ""
      uriParameters:
        bsasId:
          description: 'The unique identifier of the summary calculation.<br><br>Must conform to the regular expression: `^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
          type: string
          example: f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c
      /adjust:
        post: !include submit_foreign_property_accounting_adjustments.raml