is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBsasId
  - errors.ruleNotForeignProperty
  - errors.ruleNoAdjustmentsMade
  - errors.clientOrAgentNotAuthorised
  - errors.bsasNotFound
displayName: Retrieve a Foreign Property Business' Summary Adjustments
description: This endpoint allows the developer to request the adjustments made to a specific Foreign Property Business Source Adjustable Summary, by quoting it's identifier. A National Insurance number and BSAS ID are required. The BSAS ID quoted must be for a Foreign Property Business and previously adjusted.
(annotations.sandboxData): !include scenarios/retrieve_foreign_property_adjustments.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_foreign_property_adjustments.json
        examples:
          adjustments_full:
            description: Retrieve Foreign Property Business' Summary Adjustments example
            value: !include examples/adjustments/retrieve_foreign_property_adjustments.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.