#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid
                value:
                  code: FORMAT_NINO
  incorrectOrEmptyBodySubmitted:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBodySubmitted:
                description: An empty or non-matching body was submitted
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSelfEmploymentId:
                description: The format of the self-employment ID is not valid
                value:
                  code: FORMAT_SELF_EMPLOYMENT_ID
  ruleSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSelfEmploymentId:
                description: A self-employment ID can only be supplied for a self-employment business type
                value:
                  code: RULE_SELF_EMPLOYMENT_ID
  rulePeriodicDataIncomplete:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rulePeriodicDataIncomplete:
                description: One or more Periodic updates are missing for this accounting period
                value:
                  code: RULE_PERIODIC_DATA_INCOMPLETE
  formatStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatStartDate:
                description: The format of the supplied accounting period start date is invalid
                value:
                  code: FORMAT_START_DATE
  formatEndDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEndDate:
                description: The format of the supplied accounting period end date is invalid
                value:
                  code: FORMAT_END_DATE
  formatTypeOfBusiness:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTypeOfBusiness:
                description: The format of the supplied type of business is not valid
                value:
                  code: FORMAT_TYPE_OF_BUSINESS
  ruleEndDateBeforeStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleEndDateBeforeStartDate:
                description: The accounting period end date value is before the start date
                value:
                  code: RULE_END_DATE_BEFORE_START_DATE
  ruleAccountingPeriodNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleAccountingPeriodNotSupported:
                description: The specified accounting period is not supported, that is, the accounting period specified falls before the minimum tax year value
                value:
                  code: RULE_ACCOUNTING_PERIOD_NOT_SUPPORTED
  ruleAccountingPeriodNotEnded:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleAccountingPeriodNotEnded:
                description: The accounting period has not ended
                value:
                  code: RULE_ACCOUNTING_PERIOD_NOT_ENDED
  ruleNoAccountingPeriod:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoAccountingPeriod:
                description: The supplied accounting period does not exist
                value:
                  code: RULE_NO_ACCOUNTING_PERIOD
  triggerNotFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: The supplied income source could not be found
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED