is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBsasId
  - errors.formatAdjustedStatus
  - errors.ruleNotSelfEmployment
  - errors.ruleNoAdjustmentsMade
  - errors.clientOrAgentNotAuthorised
  - errors.bsasNotFound
  - queryParameters.adjustedStatusOptional
displayName: Retrieve a Self-Employment Business Source Adjustable Summary (BSAS) [test only]
description: This endpoint allows the user to request a specific Business Source Adjustable Summary using a unique identifier. By default, when it is available the adjusted summary will be returned. A filter can be set to specify whether the original or the adjusted is to be returned.
(annotations.sandboxData): !include scenarios/retrieve_se.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_se_bsas.json
        example: !include examples/retrieveBsas/retrieve_se_bsas.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.