is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBsasId
  - errors.formatAdjustmentValue
  - errors.incorrectOrEmptyBodySubmitted
  - errors.ruleRangeInvalid
  - errors.ruleNotSelfEmployment
  - errors.ruleSummaryStatusInvalid
  - errors.ruleSummaryStatusSuperseded
  - errors.ruleAlreadyAdjusted
  - errors.ruleOverConsolidatedExpensesThreshold
  - errors.ruleTradingIncomeAllowanceExceeded
  - errors.ruleResultingValueNotPermitted
  - errors.bsasNotFound
  - errors.clientOrAgentNotAuthorised
displayName: Submit an Adjustment to a Self-Employment Business Summary [test only]
description: This endpoint allows the user to provide accounting adjustments against a specified Business Source Adjustable Summary quoting its unique identifier. The BSAS ID quoted must be for a Self-Employment Business and it must not have been adjusted, previously.
(annotations.sandboxData): !include scenarios/submit_se_adjustments.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/submit_se_adjustments.json
    examples:
      adjustments_full:
        description: Full Expenses
        value: !include examples/adjustments/submit_se_adjustments_full.json
      adjustments_consolidated:
        description: Consolidated Expenses
        value: !include examples/adjustments/submit_se_adjustments_consolidated.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/submit_adjustments_response.json
        example: !include examples/adjustments/submit_se_adjustment_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.