is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatStartDate
  - errors.formatEndDate
  - errors.formatTypeOfBusiness
  - errors.formatSelfEmploymentId
  - errors.incorrectOrEmptyBodySubmitted
  - errors.ruleSelfEmploymentId
  - errors.ruleEndDateBeforeStartDate
  - errors.ruleAccountingPeriodNotSupported
  - errors.ruleAccountingPeriodNotEnded
  - errors.rulePeriodicDataIncomplete
  - errors.ruleAccountingPeriodNotFound
  - errors.notFound
displayName: Trigger a Business Source Accounting Summary (BSAS) [test only]
description: This endpoint allows the user to generate an end of accounting period Business Source Accounting Summary (BSAS) of the income and expenditure for a specified business for a given accounting period. A BSAS must be generated before accounting adjustments are to be entered.
(annotations.sandboxData): !include scenarios/trigger.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/trigger_request.json
    examples:
     example-1:
      description: Self-employment Trigger
      value: !include examples/trigger_se_request.json.json
     example-2:
      description: UK Property Non-FHL Trigger
      value: !include examples/trigger_non_fhl_request.json
responses:
  201:
    body:
      application/json:
        type: !include schemas/trigger_response.json
        example: !include examples/trigger_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.